name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
     tags:
     - 1.'*'
     
jobs:
  # This workflow contains a single job called "Build"
  Build:
    runs-on: [windows-latest]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore OrderProcessing.sln

    - name: Build the Solution
      run: msbuild OrderProcessing.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeleteExistingFiles=True /p:configuration="Release" /p:PublishUrl="../_build"
    
    - name: Process version of the tag
      id: version
      uses: ncipollo/semantic-version-action@v1
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps.version.outputs) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump previous tag
      env:
        PREVIOUS_TAG: ${{ steps.version.outputs.previous_tag }}
      run: echo "$PREVIOUS_TAG"
    
   # - name: 'Generate Version'
   #   id: version
   #   uses: fregante/daily-version-action@v1
      
   # - name: Upload artifact with version
   #   uses: actions/upload-artifact@v1.0.0
   #   with:
   #         name: GitHubActionMVCDemo-${{ steps.version.outputs.version }}
   #         path: "./_build"
