# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
 # push:
 #   branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Get version
      id: semver
      uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
      with:
           tag: ${{ github.ref }}
       
    - name: Echo Semver
      run: echo "${{ steps.semver.outputs.non-prefixed }}"     
